# Cloudformation Terraform module for a Linux Watchmaker instance

module "lx-instance" {
  source = "./modules/lx-instance"

  Name                   = "${var.Name}"
  AmiId                  = "${var.AmiId}"
  AmiDistro              = "${var.AmiDistro}"
  AppScriptParams        = "${var.AppScriptParams}"
  AppScriptShell         = "${var.AppScriptShell}"
  AppScriptUrl           = "${var.AppScriptUrl}"
  AppVolumeDevice        = "${var.AppVolumeDevice}"
  AppVolumeMountPath     = "${var.AppVolumeMountPath}"
  AppVolumeType          = "${var.AppVolumeType}"
  AppVolumeSize          = "${var.AppVolumeSize}"
  KeyPairName            = "${var.KeyPairName}"
  InstanceType           = "${var.InstanceType}"
  InstanceRole           = "${var.InstanceRole}"
  PrivateIp              = "${var.PrivateIp}"
  NoPublicIp             = "${var.NoPublicIp}"
  NoReboot               = "${var.NoReboot}"
  NoUpdates              = "${var.NoUpdates}"
  SecurityGroupIds       = "${var.SecurityGroupIds}"
  SubnetId               = "${var.SubnetId}"
  PypiIndexUrl           = "${var.PypiIndexUrl}"
  WatchmakerConfig       = "${var.WatchmakerConfig}"
  WatchmakerEnvironment  = "${var.WatchmakerEnvironment}"
  WatchmakerOuPath       = "${var.WatchmakerOuPath}"
  WatchmakerComputerName = "${var.WatchmakerComputerName}"
  WatchmakerAdminGroups  = "${var.WatchmakerAdminGroups}"
  WatchmakerAdminUsers   = "${var.WatchmakerAdminUsers}"
  WatchmakerS3Source     = "${var.WatchmakerS3Source}"
  CfnEndpointUrl         = "${var.CfnEndpointUrl}"
  CfnGetPipUrl           = "${var.CfnGetPipUrl}"
  CfnBootstrapUtilsUrl   = "${var.CfnBootstrapUtilsUrl}"
  ToggleCfnInitUpdate    = "${var.ToggleCfnInitUpdate}"
}
